;(prelude-require-packages '(evil))
;(require 'evil)
;(evil-mode 1)
(key-chord-define-global ",f" 'ido-find-file)
(key-chord-define-global ",b" 'ido-switch-buffer)
(key-chord-define-global ",s" 'save-buffer)
(global-set-key [f1] '(lambda () (interactive) (jump-to-register ?1)))
(global-set-key [f2] '(lambda () (interactive) (jump-to-register ?2)))
(global-set-key [f3] '(lambda () (interactive) (jump-to-register ?3)))
(global-set-key [f4] '(lambda () (interactive) (jump-to-register ?4)))
(global-set-key [\C-f1] '(lambda () (interactive) (point-to-register ?1)))
(global-set-key [\C-f2] '(lambda () (interactive) (point-to-register ?2)))
(global-set-key [\C-f3] '(lambda () (interactive) (point-to-register ?3)))
(global-set-key [\C-f4] '(lambda () (interactive) (point-to-register ?4)))
